# Generated by Django 3.2.10 on 2021-12-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='著者名')),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='タイトル')),
                ('body', models.TextField(default='', null=True, verbose_name='本文')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='blogs.author')),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
    ]
